name: 'Prettier action'
description: 'Runs a composite Prettier action'

runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
              node-version: 20
              check-latest: true
              cache: 'pnpm'
        - run: pnpm i
          shell: bash
        - run: pnpm run format-check
          shell: bash
