name: 'Types action'
description: 'Runs a composite Types action'

runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v4
        - run: corepack enable
          shell: bash
        - uses: actions/setup-node@v4
          with:
              node-version: 20
              check-latest: true
              cache: 'pnpm'
        - run: pnpm i
          shell: bash
        - run: pnpm run workspace:check-types
          shell: bash
