name: 'Types action'
description: 'Runs a composite Types action'

runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v4
        - run: corepack enable
          shell: bash
        - uses: actions/setup-node@v4
          with:
              node-version: 20
              check-latest: true
              cache: 'pnpm'
        - run: pnpm i
          shell: bash
        # TS type checking in astro require astro sync to generate types if content used
        # (Running astro dev, astro build or astro check will run the sync command as well.)
        # running in parallel (--parallel in workspace:astro-*) will result in
        # `WebSocket server error: Port is already in use` error
        # - run: pnpm run workspace:astro-sync && pnpm run workspace:astro-check && pnpm run workspace:check-types
        - run: pnpm run workspace:astro-check && pnpm run workspace:check-types
          shell: bash
