name: '@tf/maelstrom build action'
description: 'Runs a composite @tf/maelstrom build action'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
        cache: 'npm'
    - run: npm ci
      shell: bash
    - run: npm run build --workspace=@tf/maelstrom
      shell: bash
