name: 'Vitest action'
description: 'Runs a composite Vitest action'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
        cache: 'yarn'
    - run: yarn install --immutable
      shell: bash
    - run: yarn turbo:test
      shell: bash
