name: 'Lint action'
description: 'Runs a composite Lint action'

runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
              node-version: 20
              check-latest: true
              cache: 'npm'
        - run: npm ci
          shell: bash
        - run: pnpm run turbo:lint-js
          shell: bash
        - run: pnpm run turbo:lint-js-next
          shell: bash
