name: 'Lint action'
description: 'Runs a composite Lint action'

runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
              node-version: 20
              check-latest: true
              cache: 'pnpm'
        - run: pnpm i
          shell: bash
        - run: pnpm run turbo:lint-js
          shell: bash
        - run: pnpm run turbo:lint-js-next
          shell: bash
