name: build react18 efects

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-react18-efects:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run build --workspace=@tf/react18-efects
