name: build nextjs ts example

on:
  workflow_dispatch:

jobs:
  build-maelstrom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-maelstrom
