name: deploy @tf/tomekf

on:
    workflow_dispatch:

jobs:
    build-tomekf:
        uses: ./.github/workflows/build-tomekf.yml
    build-pocs:
        uses: ./.github/workflows/build-pocs.yml
    vitest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/vitest
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/lint
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prettier
    types:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/types
    bun-test:
        uses: ./.github/workflows/bun-test.yml
    deploy-tomekf:
        uses: ./.github/workflows/unsecure-deploy-tomekf.yml
        secrets: inherit
        needs: [vitest, lint, prettier, types, build-tomekf, bun-test]
